import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "./header";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],

  variable: "--font-grotesk",

  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body className="w-full  ">
        <Header />
        <div> {children}</div>
      </body>
    </html>
  );
}
